name: Build Preview App

permissions:
  contents: write

on:
  schedule:
    - cron: '0 6 * * 5'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    env:
      CI: true
    outputs:
      SHOULD_RUN: ${{ steps.compare.outputs.SHOULD_RUN }}
      LATEST_SHA: ${{ steps.compare.outputs.LATEST_SHA }}
      LAST_SHA: ${{ steps.compare.outputs.LAST_SHA }}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: 'rebelonion/Dantotsu'
          ref: 'dev'
          fetch-depth: 0
          
      - name: Download last SHA artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: 'Dantotsu-Bot/Dantotsu-Builder'
          workflow: release.yml
          name: last-sha
          path: .
        continue-on-error: true

      - name: Check for updates
        id: compare
        run: |
          LATEST_SHA=$(git rev-parse HEAD)
          echo "Latest commit SHA: $LATEST_SHA"
          echo "LATEST_SHA=${LATEST_SHA}" >> $GITHUB_OUTPUT

          if [ -f last_sha.txt ]; then
            LAST_SHA=$(cat last_sha.txt)
            echo "Last saved commit SHA: $LAST_SHA"
            echo "LAST_SHA=${LAST_SHA}" >> $GITHUB_OUTPUT
          else
            LAST_SHA=""
            echo "No previous SHA found."
            echo "LAST_SHA=${LAST_SHA}" >> $GITHUB_OUTPUT
          fi

          if [ "$LATEST_SHA" == "$LAST_SHA" ]; then
            echo "No updates found. Canceling the workflow."
            echo "SHOULD_RUN=false" >> $GITHUB_OUTPUT
          else
            echo "Updates found. Continuing workflow."
            echo "SHOULD_RUN=true" >> $GITHUB_OUTPUT
          fi

      - name: Save Current SHA for Next Run
        run: git rev-parse HEAD > last_sha.txt

      - name: Upload Current SHA as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-sha
          path: last_sha.txt

  build:
    runs-on: ubuntu-latest
    needs: check-updates
    if: ${{ needs.check-updates.outputs.SHOULD_RUN == 'true' }}
    env:
      CI: true

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: 'rebelonion/Dantotsu'
          ref: 'dev'
          fetch-depth: 0

      - name: Get Commits Since Last Run
        run: |
          if [ "${{ needs.check-updates.outputs.LAST_SHA }}" != "" ]; then
          LAST_SHA=${{ needs.check-updates.outputs.LAST_SHA }}
          else
            # Fallback to first commit if no previous SHA available
            LAST_SHA=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "Commits since $LAST_SHA"
          # Accumulate commit logs
          echo -e 'Changelogs\n---\n\n'$(git log --pretty=format:'● %s ([%h](https://github.com/rebelonion/Dantotsu/commit/%H)) - %an' $LAST_SHA..HEAD | sed 's/$/\\n/')'\n\n### Checksums\n\n| ABI | SHA-256 |\n| ------- | ------- |' > commit_logs.txt
          echo $(cat commit_logs.txt)
        shell: /usr/bin/bash -e {0}
        env:
          CI: true
        continue-on-error: true

      - name: Fetch version name
        run: |
          VERSION="v$(git rev-list --count dev)"
          sed -i '/versionNameSuffix "-fdroid"/d' app/build.gradle
          sed -i "s/versionName \"[^\"]*\"/versionName \"$VERSION\"/" app/build.gradle
          echo "Version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Inject Split ABI
        run: sed -i '/^ *defaultConfig {$/a \ \ \ \ \ \ splits {\n\ \ \ \ \ \ \ \ abi {\n\ \ \ \ \ \ \ \ \ \ enable true\n\ \ \ \ \ \ \ \ \ \ reset()\n\ \ \ \ \ \ \ \ \ \ include '\''armeabi-v7a'\'', '\''arm64-v8a'\'', '\''x86'\'', '\''x86_64'\''\n\ \ \ \ \ \ \ \ \ \ universalApk true\n\ \ \ \ \ \ \ \ }\n\ \ \ \ \ \ }' app/build.gradle

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleFdroidRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/fdroid/release
          signingKeyBase64: ${{ secrets.KEYSTORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Move APK and calculate checksum
        run: |
          mv app/build/outputs/apk/fdroid/release/app-fdroid-arm64-v8a-release-signed.apk release-fdroid-arm64-v8a-${{ env.VERSION }}.apk
          echo -e "| arm64-v8a | $(sha256sum release-fdroid-arm64-v8a-${{ env.VERSION }}.apk | cut -d' ' -f1) |" >> commit_logs.txt
          mv app/build/outputs/apk/fdroid/release/app-fdroid-armeabi-v7a-release-signed.apk release-fdroid-armeabi-v7a-${{ env.VERSION }}.apk
          echo -e "| armeabi-v7a | $(sha256sum release-fdroid-armeabi-v7a-${{ env.VERSION }}.apk | cut -d' ' -f1) |" >> commit_logs.txt
          mv app/build/outputs/apk/fdroid/release/app-fdroid-x86-release-signed.apk release-fdroid-x86-${{ env.VERSION }}.apk
          echo -e "| x86 | $(sha256sum release-fdroid-x86-${{ env.VERSION }}.apk | cut -d' ' -f1) |" >> commit_logs.txt
          mv app/build/outputs/apk/fdroid/release/app-fdroid-x86_64-release-signed.apk release-fdroid-x86_64-${{ env.VERSION }}.apk
          echo -e "| x86_64 | $(sha256sum release-fdroid-x86_64-${{ env.VERSION }}.apk | cut -d' ' -f1) |" >> commit_logs.txt

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Dantotsu
          retention-days: 5
          path: "*.apk"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body_path: commit_logs.txt
          files: |
           release-fdroid-arm64-v8a-${{ env.VERSION }}.apk
           release-fdroid-armeabi-v7a-${{ env.VERSION }}.apk
           release-fdroid-x86-${{ env.VERSION }}.apk
           release-fdroid-x86_64-${{ env.VERSION }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 5
          delete_tags: true
